import type { Metadata } from "next";
import { InfoLayout } from "../info-layout";

export const metadata: Metadata = { title:"Privacy Policy — namekind", description:"How namekind collects, uses, and protects information." };

export default function PrivacyPage() { return <InfoLayout eyebrow="Your privacy" title="Privacy Policy" intro="We designed namekind to help people explore names without surrendering unnecessary personal information.">
  <p className="updated">Last updated: August 18, 2026</p>
  <section><h2>Who operates namekind</h2><p>Namekind is operated by Harold Foster in Ohio, United States. A domain-based contact email will be published on our Contact page before public commercial launch.</p></section>
  <section><h2>Information you provide</h2><p>You may provide naming preferences, reactions to suggested names, an optional surname, and other optional naming context. In the current no-account experience, questionnaire answers and shortlists are stored locally in your browser. They are not treated as permanent account records.</p><p>The optional surname is used in your browser to preview how a full name sounds. Our AI request indicates only whether a surname was provided; it does not send the surname itself.</p></section>
  <section><h2>Information collected automatically</h2><p>Like most online services, our hosting providers may process technical information such as IP address, browser type, device information, requested pages, timestamps, and security logs. For AI rate limiting, namekind converts limited connection information into a one-way, daily-changing identifier. We store the identifier and request time—not the underlying IP address—in our usage database.</p></section>
  <section><h2>How we use information</h2><ul><li>Provide, personalize, and improve name recommendations.</li><li>Remember your temporary journey on your device.</li><li>Prevent abuse and control AI service costs.</li><li>Maintain security, reliability, and legal compliance.</li><li>Measure general service performance when analytics are introduced.</li></ul></section>
  <section><h2>AI processing</h2><p>When available, a compact preference profile and a limited list of preselected candidate names may be sent to OpenAI for final ranking. The AI is instructed to rank only supplied candidates. Reactions and preference categories may be included; your entered surname is not. If AI is unavailable or limited, namekind uses its local recommendation engine instead.</p></section>
  <section><h2>Advertising and Google</h2><p>Namekind may use Google AdSense after the site is approved and appropriate consent controls are active. Google and other advertising vendors may use cookies, web beacons, IP addresses, or similar identifiers to deliver, measure, and personalize ads where permitted. Google’s advertising cookies may enable Google and its partners to serve ads based on visits to namekind or other websites.</p><p>Visitors can manage Google ad personalization through <a href="https://adssettings.google.com" target="_blank" rel="noreferrer">Google Ads Settings</a> and can learn how Google uses partner-site information through <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer">Google’s partner-sites notice</a>. We will update this policy and activate a consent-management process before advertising begins.</p></section>
  <section><h2>Sharing and service providers</h2><p>We do not sell the personal information you directly provide. Information may be processed by service providers that help operate namekind, including hosting and security providers, OpenAI for optional refinement, and—once activated—advertising and consent providers such as Google. We may also disclose information when required by law or necessary to protect rights, safety, and service integrity.</p></section>
  <section><h2>Retention and security</h2><p>Temporary journey data remains in your browser until you clear it or restart the journey. AI rate-limit records are designed for short retention and routine deletion. Hosting and security providers may retain logs under their own policies. We use reasonable safeguards, but no online system can guarantee absolute security.</p></section>
  <section><h2>Children’s privacy</h2><p>Namekind is designed for parents and other adults choosing names; it is not directed to children under 13. We do not knowingly request personal information from children. If we learn that a child provided personal information, we will take reasonable steps to delete it.</p></section>
  <section><h2>Your choices and rights</h2><p>You can clear locally saved journey information through the site’s “Start over” control or your browser settings. Depending on where you live, you may have rights concerning access, correction, deletion, or certain uses of personal information. A privacy request channel will be listed on the Contact page before public launch.</p></section>
  <section><h2>Changes</h2><p>We may update this policy as namekind adds accounts, analytics, advertising, shared journeys, or other features. The updated date will show when revisions take effect.</p></section>
</InfoLayout> }
