export type NameCategory = {
  slug:string; audience:"baby"|"pet"; eyebrow:string; title:string; description:string; intro:string;
  names:string[]; guidance:string[]; faq:Array<{question:string;answer:string}>; pairs?:Array<[string,string]>;
};

export const nameCategories:NameCategory[] = [
  {slug:"unique-baby-names",audience:"baby",eyebrow:"Distinctive, not invented",title:"Unique baby names with meaning",description:"Explore uncommon baby names that feel established, meaningful, and distinctive without being difficult to wear.",intro:"A unique name does not need to feel unfamiliar. These choices sit beyond the most obvious favorites while keeping genuine history, intuitive sounds, or meaningful roots.",names:["Juniper","Amara","Quinn","Sienna","Eden","Maeve","Ayla","Leilani","Iris","Adriel","Gael","Atlas","Emiliano","Silas","Enzo","Micah"],guidance:["Say each name in an everyday voice, not only an announcement voice.","Check initials, likely nicknames, and common spelling assumptions.","Choose distinction that still feels natural for your family."],faq:[{question:"What makes a baby name unique?",answer:"A unique name feels less commonly encountered while remaining meaningful and usable. Popularity varies by location, culture, spelling, and year."},{question:"Should a unique name be outside the Top 100?",answer:"Not necessarily. A familiar name can still feel distinctive in your community, while an uncommon spelling may be more widespread than expected."}]},
  {slug:"nature-inspired-baby-names",audience:"baby",eyebrow:"Rooted in the natural world",title:"Nature-inspired baby names",description:"Discover botanical, celestial, seasonal, and landscape-inspired baby names with meanings and pairing ideas.",intro:"Nature names can feel peaceful, adventurous, bright, or quietly strong. This collection moves from flowers and trees to seasons, waterways, and the night sky.",names:["Violet","Lily","Aurora","Hazel","Ivy","Willow","Iris","Daisy","Autumn","Juniper","Rowan","Brooks","Atlas","Silas","Luna","Nova"],guidance:["Decide whether you prefer a direct word name or a subtler nature meaning.","Balance a vivid first name with the rhythm of your surname.","Consider the feeling of the image as well as its literal meaning."],faq:[{question:"What are popular nature-inspired baby names?",answer:"Current favorites include Violet, Lily, Hazel, Willow, Ivy, Aurora, and Rowan."},{question:"Are nature names gender-neutral?",answer:"Many are. Rowan, River-style choices, and botanical or landscape names often cross traditional gender categories."}]},
  {slug:"gender-neutral-baby-names",audience:"baby",eyebrow:"Open, modern, and versatile",title:"Gender-neutral baby names",description:"Explore gender-neutral baby names with origins, meanings, popularity context, and sibling-name ideas.",intro:"Gender-neutral names offer flexibility without sacrificing history or personality. Some began as surnames, some have multicultural use, and others have simply broadened over time.",names:["Avery","Riley","Quinn","Harper","Rowan","Cameron","Kai","Angel","Emery","Eden","Sage","River","Jordan","Parker","Finley","Morgan"],guidance:["Look at current usage, but remember that naming patterns change over time.","Test the name with your surname and any sibling names.","Choose the name for its sound and meaning—not only its category."],faq:[{question:"What is a gender-neutral baby name?",answer:"It is a name used across more than one gender. Usage can differ by country, community, culture, and generation."},{question:"Which gender-neutral names are popular now?",answer:"Avery, Riley, Harper, Quinn, Rowan, and Cameron are recognizable contemporary choices."}]},
  {slug:"twin-names-same-first-letter",audience:"baby",eyebrow:"Connected, with separate identities",title:"Twin names with the same first letter",description:"Find twin baby-name pairs that share an initial without rhyming or feeling too closely matched.",intro:"A shared initial creates an immediate connection. The strongest pairs still use different rhythms, endings, and nickname possibilities so each child’s name remains distinct.",names:["Amelia","Arthur","Clara","Caleb","Eleanor","Ethan","Lily","Leo","Mia","Mateo","Noah","Naomi","Olivia","Oliver","Ruby","Roman"],pairs:[["Amelia","Arthur"],["Clara","Caleb"],["Eleanor","Ethan"],["Lily","Leo"],["Mia","Mateo"],["Noah","Naomi"],["Olivia","Oliver"],["Ruby","Roman"]],guidance:["Avoid pairs that rhyme or differ by only one or two sounds.","Give each child a clearly different everyday nickname.","Say the names separately and together with your surname."],faq:[{question:"Should twin names start with the same letter?",answer:"They can, but they do not need to. A shared initial works best when the names still have different sounds and identities."},{question:"How do I keep matching twin names distinct?",answer:"Use different endings, syllable counts, stressed sounds, and nicknames. Avoid near-rhymes and names that are easily misheard."}]},
  {slug:"popular-dog-names",audience:"pet",eyebrow:"Friendly favorites",title:"Popular dog names with personality",description:"Explore popular dog names with meanings, nicknames, calling tips, and styles for every kind of dog.",intro:"A strong dog name should feel good in affectionate moments and remain clear when called outside. These favorites combine warmth, personality, and practical sound.",names:["Luna","Max","Bella","Charlie","Milo","Daisy","Lucy","Cooper","Teddy","Bailey","Rocky","Buddy","Bear","Tucker","Winston","Murphy","Scout","Duke","Ranger","Apollo"],guidance:["Use one or two clear syllables when easy recall is a priority.","Avoid a name that closely resembles a training cue or household name.","Try the name in a happy voice, a calm voice, and across a yard."],faq:[{question:"What are popular dog names?",answer:"Luna, Max, Bella, Charlie, Milo, Daisy, Cooper, Teddy, and Bailey repeatedly appear among current favorites."},{question:"What makes a dog name easy to call?",answer:"Clear consonants, a distinct vowel pattern, and one or two strong syllables can make everyday calling easier."}]},
  {slug:"popular-cat-names",audience:"pet",eyebrow:"Clever, cozy, and full of character",title:"Popular cat names and their meanings",description:"Explore popular cat names with meanings, personality, nicknames, and similar choices for kittens and adult cats.",intro:"Cat names can be elegant, mischievous, cozy, or wonderfully strange. These choices range from polished human names to food, mythology, and night-sky favorites.",names:["Luna","Milo","Bella","Leo","Nala","Lily","Coco","Charlie","Lucy","Simba","Cleo","Oliver","Loki","Nova","Jasper","Shadow","Mochi","Salem","Callie","Pepper"],guidance:["Let appearance inspire you, but leave room for personality to emerge.","Choose a name everyone in the household can say comfortably.","Test the full name and the nickname you will probably use most."],faq:[{question:"What are popular cat names?",answer:"Luna, Milo, Bella, Leo, Nala, Lily, Simba, Cleo, Loki, and Oliver are widely recognized cat-name favorites."},{question:"Do cats respond better to certain names?",answer:"Consistency and tone matter more than one perfect formula. A short, distinct sound can be convenient for repeated everyday use."}]},
  {slug:"nature-inspired-pet-names",audience:"pet",eyebrow:"From gardens, forests, and skies",title:"Nature-inspired pet names",description:"Discover nature-inspired names for dogs, cats, and other companions, from flowers and trees to weather and wildlife.",intro:"Nature offers names that can feel soft, outdoorsy, colorful, or bold. Choose a familiar botanical favorite or follow one small detail that reminds you of your companion.",names:["Luna","Daisy","Bear","Willow","Nova","Blue","Maple","Sunny","Poppy","Olive","Ivy","Hazel","Oakley","Moose","Goose","Shadow","Ruby","Stella","Pepper","Honey"],guidance:["Match the scale of the image to your pet—or enjoy the contrast.","Consider color, habitat, season, and personality rather than species alone.","Use a nickname to soften a dramatic nature word."],faq:[{question:"What are good nature names for pets?",answer:"Luna, Willow, Daisy, Bear, Maple, Poppy, Hazel, Ivy, Nova, and Sunny are approachable nature-inspired choices."},{question:"Can a nature name work for any pet?",answer:"Yes. The association, sound, and personality fit matter more than the animal’s species."}]},
  {slug:"food-inspired-pet-names",audience:"pet",eyebrow:"Sweet, spicy, and playful",title:"Food-inspired pet names",description:"Browse adorable food-inspired pet names with meanings, nicknames, and personality ideas for dogs and cats.",intro:"Food names bring instant warmth and humor. They work especially well when a pet’s coloring, size, sweetness, or spicy personality makes the connection feel personal.",names:["Mochi","Oreo","Peanut","Pepper","Ginger","Honey","Coco","Maple","Olive","Biscuit","Cookie","Bean","Waffles","Pickles","Pumpkin","Peaches","Muffin","Toffee","Chai","Noodle"],guidance:["Choose a word that stays charming after the puppy or kitten stage.","Make sure the sound remains distinct from household cues.","Try a polished full name with a playful food nickname."],faq:[{question:"What are cute food names for pets?",answer:"Mochi, Oreo, Peanut, Pepper, Ginger, Honey, Maple, Biscuit, Cookie, and Olive are enduring favorites."},{question:"Why are food names popular for pets?",answer:"They are affectionate, memorable, and often connect naturally with a pet’s appearance or personality."}]},
];

export const babyCategories=nameCategories.filter(item=>item.audience==="baby");
export const petCategories=nameCategories.filter(item=>item.audience==="pet");
export const categoryByKey=new Map(nameCategories.map(item=>[`${item.audience}:${item.slug}`,item]));
