import type { Metadata } from "next";
import { InfoLayout } from "../info-layout";

export const metadata: Metadata = { title:"Terms of Use — namekind", description:"Terms governing use of the namekind service." };

export default function TermsPage() { return <InfoLayout eyebrow="The ground rules" title="Terms of Use" intro="These terms help keep namekind useful, respectful, and available to everyone.">
  <p className="updated">Last updated: August 18, 2026</p>
  <section><h2>Agreement</h2><p>These Terms govern your use of namekind, operated by Harold Foster in Ohio, United States. By using the service, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the service.</p></section>
  <section><h2>Who may use namekind</h2><p>Namekind is intended for adults and is not directed to children under 13. If you use the service on behalf of another person or organization, you represent that you have authority to accept these Terms for them.</p></section>
  <section><h2>What the service provides</h2><p>Namekind offers tools for exploring and comparing names. Recommendations may be produced by curated data, preference-based ranking, and artificial intelligence. The service is for inspiration and general information only.</p></section>
  <section><h2>No guarantee of accuracy</h2><p>Name meanings, origins, spellings, pronunciations, cultural associations, popularity, and suitability can differ among sources and communities. We do not guarantee that any description or recommendation is complete, current, culturally appropriate in every context, or suitable for your particular circumstances. You are responsible for independently researching a name before making a decision.</p></section>
  <section><h2>Acceptable use</h2><p>You may not misuse namekind, interfere with its operation, bypass rate limits or security measures, scrape or systematically extract the name database, send automated requests without permission, attempt unauthorized access, introduce malicious code, or use the service in violation of law or another person’s rights.</p></section>
  <section><h2>Your input</h2><p>You remain responsible for information you enter. Do not submit sensitive personal information or information you do not have permission to use. You grant us permission to process submitted information only as necessary to provide, secure, and improve the service as described in our Privacy Policy.</p></section>
  <section><h2>Intellectual property</h2><p>The namekind branding, interface, original writing, recommendation logic, and site materials are owned by Harold Foster or used with permission and are protected by applicable law. Names themselves and factual information may not be proprietary, but the service’s selection, presentation, and original content may be.</p></section>
  <section><h2>Third-party services and advertising</h2><p>Namekind may rely on hosting, AI, analytics, consent, and advertising providers. Third-party services have their own terms and privacy practices. Advertisements do not constitute an endorsement, and any transaction with an advertiser is between you and that advertiser.</p></section>
  <section><h2>Availability and changes</h2><p>We may modify, suspend, limit, or discontinue any part of namekind. We may change recommendation pools, AI limits, features, or these Terms. Continued use after updated Terms become effective constitutes acceptance of the revised Terms.</p></section>
  <section><h2>Disclaimer</h2><p>To the fullest extent permitted by law, namekind is provided “as is” and “as available,” without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, noninfringement, accuracy, or uninterrupted availability.</p></section>
  <section><h2>Limitation of liability</h2><p>To the fullest extent permitted by law, Harold Foster and namekind will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost profits or data, or decisions made using the service. Where liability cannot be excluded, aggregate liability will not exceed the greater of amounts you paid to use namekind during the preceding twelve months or US $100.</p></section>
  <section><h2>Governing law</h2><p>These Terms are governed by the laws of the State of Ohio and applicable United States federal law, without regard to conflict-of-law principles. Nothing in these Terms limits rights that cannot lawfully be waived.</p></section>
  <section><h2>Contact</h2><p>A domain-based legal contact address will be added to the Contact page before public commercial launch.</p></section>
</InfoLayout> }
